package com.eli.ads.user.permission;

public enum PermissionEnum {

    REGISTER_DENTIST,

    BOOK_APPOINTMENT,
    VIEW_APPOINTMENT,
    CANCEL_APPOINTMENT,
    RESCHEDULE_APPOINTMENT,

    REGISTER_PATIENT,
    LIST_PATIENTS,
    VIEW_PATIENT,
    UPDATE_PATIENT,
    DELETE_PATIENT,

    LIST_ADDRESSES,
    LIST_DENTISTS, DELETE_DENTIST, VIEW_DENTIST, UPDATE_DENTIST, SEARCH_PATIENT, CREATE_SURGERY, VIEW_SURGERY, LIST_SURGERIES, VIEW_BILL, UPDATE_BILL;


}
