name: CI/CD - Docker Image Build and Push on Tag

on:
  push:
    tags:
      - 'v*'

    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: ads-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Remove Docker cache (clean build)
        run: |
          docker builder prune -af

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: true
          tags: |
            ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_VERSION=${{ env.VERSION }}
            APP_PORT=8080

#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v1
#        with:
#          tag_name: v${{ env.VERSION }}
#          name: Release v${{ env.VERSION }}
#          generate_release_notes: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
#
#      - name: Upload docker-compose.yml as asset
#        uses: softprops/action-gh-release@v1
#        with:
#          files: docker-compose.yml
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
